### ISSUE TITLE
[orx-gui] App crashes when minimized on Windows

### ISSUE THREAD

**Issue by shi-weili** [openrndr/orx#183]
**Describe the bug**
When using `orx-gui`, the app will crash on Windows 10 when the window is minimized.

**To Reproduce**
Build and run `orx-gui/src/demo/kotlin/DemoSimple01.kt`, then click the minimize button of the app window.

**Expected behavior**
The app crashes with console output similar to the following:

```
Exception in thread "main" java.lang.IllegalArgumentException: unsupported resolution (0×0)
	at org.openrndr.draw.RenderTargetKt.renderTarget(RenderTarget.kt:411)
	at org.openrndr.draw.RenderTargetKt.renderTarget$default(RenderTarget.kt:408)
	at org.openrndr.panel.ControlManager.resize(ControlManager.kt:376)
	at org.openrndr.panel.ControlManager.access$resize(ControlManager.kt:72)
	at org.openrndr.panel.ControlManager$setup$11.invoke(ControlManager.kt:346)
	at org.openrndr.panel.ControlManager$setup$11.invoke(ControlManager.kt:72)
	at org.openrndr.events.Event.deliver(Event.kt:110)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.deliverEvents(ApplicationGLFWGL3.kt:859)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:883)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:810)
	at org.openrndr.Application$Companion.run(Application.kt:46)
	at org.openrndr.ApplicationKt.application(Application.kt:100)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:109)
	at DemoSimple01Kt.main(DemoSimple01.kt:12)
	at DemoSimple01Kt.main(DemoSimple01.kt)
```

**Context:**
OS and version: Windows 10 Pro 19041.867
OpenRNDR version: 0.3.45
Java Version: openjdk-15.0.2

**Additional context**
If `extend(gui)` is commented out, the app won't crash when minimized.
The app doesn't crash when minimized on macOS.

**Comment by edwinRNDR** [comment]
Hi @shi-weili, you can try to upgrade to openrndr 0.3.47-rc.2  + orx 0.3.57.rc1, this should have that error fixed

**Comment by shi-weili** [comment]
Thanks @edwinRNDR ! Tested and it works correctly.
