### ISSUE TITLE
[orx-shapes] contour.roundCorners fails with `use moveTo first`

### ISSUE THREAD

**Issue by hamoid** [openrndr/orx#333]
### Operating System

Linux

### OPENRNDR version

0.4.5-SNAPSHOT

### ORX version

0.4.5-SNAPSHOT

### Describe the bug

```
[main] ERROR org.openrndr.internal.gl3.ApplicationGLFWGL3 - OPENRNDR program ended with exception. (use moveTo first)}
Exception in thread "main" java.lang.IllegalArgumentException: use moveTo first
	at org.openrndr.shape.ContourBuilder.lineTo(ShapeBuilder.kt:139)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt$chamferCorners$2.invoke(ChamferCorners.kt:100)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt$chamferCorners$2.invoke(ChamferCorners.kt:50)
	at org.openrndr.shape.ShapeBuilderKt.contour(ShapeBuilder.kt:494)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt.chamferCorners(ChamferCorners.kt:50)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt.chamferCorners$default(ChamferCorners.kt:38)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt.roundCorners(ChamferCorners.kt:131)
	at org.openrndr.extra.shapes.operators.ChamferCornersKt.roundCorners$default(ChamferCorners.kt:130)
	at RoundKt$main$1$1.invokeSuspend(round.kt:28)
	at RoundKt$main$1$1.invoke(round.kt)
	at RoundKt$main$1$1.invoke(round.kt)
	at org.openrndr.ApplicationBuilderJVM$program$1.setup(ApplicationBuilder.kt:122)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3$loop$15.invokeSuspend(ApplicationGLFWGL3.kt:948)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:947)
	at org.openrndr.Application.run$openrndr_application(Application.kt:92)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:103)
	at RoundKt.main(round.kt:9)
	at RoundKt.main(round.kt)
```

### Steps to reproduce the bug

```
import org.openrndr.application
import org.openrndr.extra.shapes.operators.roundCorners
import org.openrndr.math.Vector2
import org.openrndr.math.YPolarity
import org.openrndr.shape.Segment2D
import org.openrndr.shape.ShapeContour

fun main() = application {
    program {
        val bad = ShapeContour(
            listOf(
                Segment2D(
                    Vector2(53.0, 23.0),
                    Vector2(62.0, 24.0),
                ),
                Segment2D(
                    Vector2(62.0, 24.0),
                    listOf(Vector2(67.0, 32.0)),
                    Vector2(63.0, 39.0)
                ),
                Segment2D(
                    Vector2(63.0, 39.0),
                    Vector2(53.0, 23.0)
                )
            ), true, YPolarity.CW_NEGATIVE_Y
        )
        val r = bad.roundCorners(2.0)
        extend {
            drawer.contour(r)
            drawer.contour(bad)
        }
    }
}
```

**Comment by hamoid** [comment]
If I remove this line

https://github.com/openrndr/orx/blob/af6d35c59bca8a932721e43399e0a6c9d320e23a/orx-shapes/src/commonMain/kotlin/operators/ChamferCorners.kt#L68

this case works. Although then I notice that it only rounds linear segments but not the corner between a linear and a curved segment.

**Comment by edwinRNDR** [comment]
the initial moveTo is skipped for open contours to prevent this problem:
<img width="832" alt="image" src="https://github.com/openrndr/orx/assets/983309/68d787e0-03e4-43ab-995a-380d36efb022">

I suspect this code was never tested properly and it is also missing a demo.
