### ISSUE TITLE
[orx-jumpflood] DistanceField crashes with orx-olive

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/orx#36]
```
org.openrndr.internal.gl3.GL3Exception: GL ERROR: GL_INVALID_OPERATION no current program object (0), or uniform type mismatch (no program
	at org.openrndr.internal.gl3.ErrorGL3Kt.checkGLErrors(ErrorGL3.kt:20)
	at org.openrndr.internal.gl3.ShaderGL3.postUniformCheck(ShaderGL3.kt:737)
	at org.openrndr.internal.gl3.ShaderGL3.uniform(ShaderGL3.kt:595)
	at org.openrndr.draw.Filter.apply(Filter.kt:106)
	at org.openrndr.draw.Filter.apply(Filter.kt:69)
	at org.openrndr.draw.Filter.apply(Filter.kt:171)
	at org.openrndr.extra.jumpfill.JumpFlooder.jumpFlood(JumpFlood.kt:84)
	at org.openrndr.extra.jumpfill.DistanceField.apply(DistanceField.kt:40)
	at org.openrndr.draw.Filter.apply(Filter.kt:171)
	at org.openrndr.extra.compositor.Layer.drawLayer(Compositor.kt:106)
	at org.openrndr.extra.compositor.Layer$drawLayer$$inlined$let$lambda$2.invoke(Compositor.kt:79)
	at org.openrndr.extra.compositor.Layer$drawLayer$$inlined$let$lambda$2.invoke(Compositor.kt:29)
	at org.openrndr.draw.DrawerKt.isolated(Drawer.kt:787)
	at org.openrndr.draw.DrawerKt.isolatedWithTarget(Drawer.kt:798)
	at org.openrndr.extra.compositor.Layer.drawLayer(Compositor.kt:73)
	at org.openrndr.extra.compositor.Composite.draw(Compositor.kt:164)
	at ScriptingHost5bb14946_Line_2$1$1$1.invoke(ScriptingHost5bb14946_Line_2.kts:42)
	at ScriptingHost5bb14946_Line_2$1$1$1.invoke(ScriptingHost5bb14946_Line_2.kts:13)
	at org.openrndr.Program$extend$functionExtension$2.beforeDraw(Program.kt:120)
	at org.openrndr.Program.drawImpl(Program.kt:241)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:659)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:590)
	at org.openrndr.Application$Companion.run(Application.kt:33)
	at org.openrndr.ApplicationKt.application(Application.kt:75)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:108)
	at Sketch02Kt.main(Sketch02.kt:20)
	at Sketch02Kt.main(Sketch02.kt)
```

**Comment by edwinRNDR** [comment]
Fixed in https://github.com/openrndr/orx/commit/857b8714fe5b931de12f443a390e3df85ca9a128
